// File generated by flutterfire configure
// This file needs to be configured with your Firebase project credentials
// Run: flutterfire configure
// Or manually update the values below with your Firebase project config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnlD9obiNd9zxNtkxRjjbPYE28v8q6dU',
    appId: '1:684415395438:web:e0d05cd83bf3fe1553287f',
    messagingSenderId: '684415395438',
    projectId: 'nahdi-man',
    authDomain: 'nahdi-man.firebaseapp.com',
    storageBucket: 'nahdi-man.firebasestorage.app',
    measurementId: 'G-XSB3PS333W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4I_DVsy4x5YmxhTU6mRdVLJKWPfZmPc',
    appId: '1:684415395438:android:f8ffe72d2486529853287f',
    messagingSenderId: '684415395438',
    projectId: 'nahdi-man',
    storageBucket: 'nahdi-man.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXshDVtTPVNccYqHu09wBT4IA6KkY1O8',
    appId: '1:684415395438:ios:05f8bbb54804c7cf53287f',
    messagingSenderId: '684415395438',
    projectId: 'nahdi-man',
    storageBucket: 'nahdi-man.firebasestorage.app',
    iosBundleId: 'com.example.nahdiApiDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.nahdiApiDashboard',
  );
}

